
bands:

  band_1:
    file_path: "./1.fits"
    background_mode: "const"
    move_factor: .5
    area_ratio: 0.90
    s_sigma: .0
    G_fit: false
    skip_reduction: true
    crop: [500, 500, 1000, 1000]

  band_2:
    file_path: "./2.fits"
    background_mode: "morph"
    move_factor: 8
    area_ratio: 0.90
    s_sigma: 4.0
    G_fit: true
    skip_reduction: false
    crop: [500, 500, 1000, 1000]

  band_3:
    file_path: "./3.fits"
    background_mode: "const"
    move_factor: 8
    area_ratio: 0.93
    s_sigma: 2.7
    G_fit: true
    skip_reduction: true
    crop: [ 500, 500, 1000, 1000 ]

  band_4:
    file_path: "./4th.fits"
    background_mode: "const"
    move_factor: 3
    area_ratio: 0.93
    s_sigma: 3.13
    G_fit: false
    skip_reduction: true
    crop: [500, 500, 1000, 1000]


